#!/usr/bin/env node
// Rewrites the modulepreload list in index.html from the files that exist (js/*.js modules + content/**/*.js),
// so every module downloads in parallel. Run after adding a unit:  node tools/sync-preload.mjs
import fs from 'node:fs';
import path from 'node:path';
const walk = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]));
const mods = [
  'js/app.js',
  ...fs.readdirSync('js').filter((f) => f.endsWith('.js') && f !== 'app.js' && f !== 'calm-glass.js').sort().map((f) => `js/${f}`),
  ...walk('content').filter((f) => f.endsWith('.js')).sort(),
];
const FB = ['firebase-app.js', 'firebase-auth.js', 'firebase-firestore.js'].map((f) => `https://www.gstatic.com/firebasejs/10.12.2/${f}`);
const block = ['  <!-- preload:start (generated by tools/sync-preload.mjs) -->',
  ...mods.map((m) => `  <link rel="modulepreload" href="${m}">`),
  ...FB.map((u) => `  <link rel="modulepreload" href="${u}" crossorigin>`),
  '  <!-- preload:end -->'].join('\n');
let html = fs.readFileSync('index.html', 'utf8');
if (html.includes('<!-- preload:start')) html = html.replace(/  <!-- preload:start[\s\S]*?<!-- preload:end -->/, block);
else html = html.replace(/  <!-- Download every module at once[^\n]*\n(?:  <link rel="modulepreload"[^\n]*\n)+/, block + '\n');
fs.writeFileSync('index.html', html);
console.log(`preload list: ${mods.length} modules + Firebase`);
